# mezora theme - sauce for macchina cli

separator=""
separator_color="#ED8796"
key_color="#ED8796"
prefer_small_ascii = true

[palette]
type="Dark"
visible=true
glyph=" ⬤ "

[box]
title=" msbis "
border="rounded"
visible=true

[bar]
glyph="▮ "
hide_delimiters=true
visible=true

[randomize]
key_color=false
separator_color=false

[custom_ascii]
color="#ED8796"
path="~/.config/macchina/themes/ascii-redhat.txt"

[keys]
host=" host"
kernel=" kernel"
distro="󱄛 distro"
de = "󰊬 DE"
wm = "󰮯 WM"
packages=" packages"
terminal=" terminal"
shell=" shell"
local_ip = "󰲑 Local IP"
uptime = " Uptime"
resolution = "󰍹 Resolution"
cpu=" cpu"
cpu_load=" cpu"
memory=" memory"
battery=" battery"
